CREATE TABLE Users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE Messages (
  id SERIAL PRIMARY KEY,
  from INTEGER NOT NULL,
  date TIMESTAMP NOT NULL,
  message TEXT NOT NULL,
  roomId INTEGER NOT NULL,
  FOREIGN KEY (from) REFERENCES Users(id),
  FOREIGN KEY (roomId) REFERENCES Rooms(id)
);

CREATE TABLE Rooms (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE UserRoom (
  id SERIAL PRIMARY KEY,
  UserId INTEGER NOT NULL,
  RoomId INTEGER NOT NULL,
  FOREIGN KEY (UserId) REFERENCES Users(id),
  FOREIGN KEY (RoomId) REFERENCES Rooms(id)
);
